version: "3"

services:
  memcached:
    image: memcached:${MEMCACHED_VERSION}
    environment:
      TZ: ${TZ}
    ports: 
      - 11211:11211
    networks: 
      - default_net
    restart: always

  nginx: 
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_PORTS}
    environment:
      TZ: ${TZ}
    volumes:
      - ${SOURCE_DIR}:/var/www/html:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d:ro
      - ${NGINX_DEFAULT_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx:rw
    restart: always
    networks: 
      - default_net

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    volumes:
      - ${MYSQL_CONF_DIR}:/etc/mysql/conf.d:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    networks: 
      - default_net

  php72: 
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHALCON_VERSION: ${PHP72_PHALCON_VERSION}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
        MORE_EXTENSIONS_INSTALL: php72.sh
    environment:
      TZ: ${TZ}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_EXTRA_FILE}:/usr/local/etc/php/conf.d/php-extra.ini:ro
      - ${PHP72_FPM_CONF_EXTRA_FILE}:/usr/local/etc/php-fpm.d/php-fpm-extra.conf:ro
      - ${PHP72_LOG_DIR}:/var/log/php:rw
    restart: always
    networks: 
      - default_net

  php56: 
    build:
      context: .
      args:
        PHP_VERSION: ${PHP56_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHALCON_VERSION: ${PHP56_PHALCON_VERSION}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        MORE_EXTENSIONS_INSTALL: php56.sh
    environment:
      TZ: ${TZ}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONF_EXTRA_FILE}:/usr/local/etc/php/conf.d/php-extra.ini:ro
      - ${PHP56_FPM_CONF_EXTRA_FILE}:/usr/local/etc/php-fpm.d/php-fpm-extra.conf:ro
      - ${PHP56_LOG_DIR}:/var/log/php:rw
    restart: always
    networks: 
      - default_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - TZ=${TZ}
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always

    networks: 
      - default_net
networks:
  default_net: